owner: contactify-ag
repo: upptime

assignees:
  - cleverer
  - jeniffer9

workflowSchedule:
  uptime: "*/10 * * * *"

sites:
# Public
  - name: Contactify Website
    url: https://www.contactify.biz


# Internal
  - name: Bitwarden
    url: https://vaultwarden.contactify.biz/alive


# Digital Business Card
## Backends
### contactify-platform-api-prod
  - name: Contactify Platform API
    url: https://contacts-api.contactify.biz
  - name: Ruag Platform API
    url: https://contacts-api.ruag.com
  - name: Beyond Gravity Platform API
    url: https://contacts-api.beyondgravity.com
  - name: FIFA Platform API
    url: https://contacts-api.fifa.org
  - name: IPT Platform API
    url: https://contacts-api.ipt.ch
  - name: UMB Platform API
    url: https://contacts-api.umb.ch

### contactify-admin-api-prod
  - name: Contactify Admin API
    url: https://contacts-admin-api.contactify.biz
  - name: Beyond Gravity Admin API
    url: https://contacts-admin-api.beyondgravity.com
  - name: FIFA Admin API
    url: https://contacts-admin-api.fifa.org
  - name: IPT Admin API
    url: https://contacts-admin-api.ipt.ch
  - name: UMB Admin API
    url: https://contacts-admin-api.umb.ch

### contactify-platform-api-dev
  - name: Contactify Platform API
    url: https://contacts-api-test.contactify.biz
  - name: Ruag Platform API
    url: https://contacts-api-test.ruag.com
  - name: Beyond Gravity Platform API
    url: https://contacts-api-test.beyondgravity.com
  - name: FIFA Platform API
    url: https://contacts-api-test.fifa.org
  - name: IPT Platform API
    url: https://contacts-api-test.ipt.ch
  - name: UMB Platform API
    url: https://contacts-api-test.umb.ch

### contactify-admin-api-dev
  - name: Beyond Gravity Admin API
    url: https://contacts-admin-api-test.beyondgravity.com
  - name: FIFA Admin API
    url: https://contacts-admin-api-test.fifa.org
  - name: IPT Admin API
    url: https://contacts-admin-api-test.ipt.ch
  - name: UMB Admin API
    url: https://contacts-admin-api-test.umb.ch
  - name: Contactify Admin API
    url: https://contacts-admin-api-test.contactify.biz

### contactify-admin-api-prod
  - name: Contactify Admin API
    url: https://contacts-admin-api-test.swica.ch

### contactify-admin-api-dev
  - name: Contactify Admin API
    url: https://contacts-admin-api.swica.ch

### contactify-platform-api-prod
  - name: Contactify Platform API
    url: https://contacts-api.swica.ch

### contactify-platform-api-dev
  - name: Contactify Platform API
    url: https://contacts-api-test.swica.ch


## Frontends
### contactify-prod
  - name: Contactify Platform Frontend
    url: https://contacts.contactify.biz
  - name: Contactify Admin Frontend
    url: https://contacts-admin.contactify.biz
### contactify-dev
  - name: Contactify Platform Frontend
    url: https://contacts-test.contactify.biz
  - name: Contactify Admin Frontend
    url: https://contacts-admin-test.contactify.biz
### fifa-prod
  - name: FIFA Platform Frontend
    url: https://contacts.fifa.org
  - name: FIFA Admin Frontend
    url: https://contacts-admin.fifa.org
### fifa-dev
  - name: FIFA Platform Frontend
    url: https://contacts-test.fifa.org
  - name: FIFA Admin Frontend
    url: https://contacts-admin-test.fifa.org
### ipt-prod
  - name: IPT Platform Frontend
    url: https://contacts.ipt.ch
### ipt-dev
  - name: IPT Platform Frontend
    url: https://contacts-test.ipt.ch
### ruag-prod
  - name: RUAG Platform Frontend
    url: https://contacts.ruag.com
  - name: Beyond Gravity Platform Frontend
    url: https://contacts.beyondgravity.com
  - name: Beyond Gravity Admin Frontend
    url: https://contacts-admin.beyondgravity.com
### ruag-dev
  - name: Ruag Platform Frontend
    url: https://contacts-test.ruag.com
  - name: Beyond Gravity Platform Frontend
    url: https://contacts-test.beyondgravity.com
  - name: FIFA Admin Frontend
    url: https://contacts-admin-test.beyondgravity.com
### umb-prod
  - name: UMB Platform Frontend
    url: https://contacts.umb.ch
  - name: UMB Admin Frontend
    url: https://contacts-admin.umb.ch
### umb-dev
  - name: UMB Platform Frontend
    url: https://contacts-test.umb.ch
  - name: UMB Admin Frontend
    url: https://contacts-admin-test.umb.ch


## Old Vercel Deployments
### SWICA PROD
  - name: Contactify Platform Frontend
    url: https://contacts.swica.ch
  - name: Contactify Admin Frontend
    url: https://contacts-admin.swica.ch
### SWICA DEV
  - name: Contactify Platform Frontend
    url: https://contacts-test.swica.ch
  - name: Contactify Admin Frontend
    url: https://contacts-admin-test.swica.ch
