owner: contactify-ag
repo: upptime

assignees:
  - cleverer
  - jeniffer9

status-website:
  name: Service Status
  logoUrl: https://contacts.contactify.biz/assets/logos/black.svg
  cname: status.contactify.biz
  robotsText: "User-agent: * \n Disallow: /"
  metaTags:
    - name: "robots"
      content: "noindex"

sites:
# Public
  - name: Contactify Website
    url: https://www.contactify.biz

# Digital Business Card
## Backends
### contactify-platform-api-prod
  - name: PROD Contactify Platform API
    url: https://contacts-api.contactify.biz

### contactify-admin-api-prod
  - name: PROD Contactify Admin API
    url: https://contacts-admin-api.contactify.biz

### contactify-platform-api-dev
  - name: DEV Contactify Platform API
    url: https://contacts-api-test.contactify.biz/api/health
    __dangerous__body_degraded: "Degraded"

### contactify-admin-api-dev
  - name: DEV Contactify Admin API
    url: https://contacts-admin-api-test.contactify.biz/api/health
    __dangerous__body_degraded: "Degraded"

## Frontends
### contactify-prod
  - name: PROD Contactify Platform Frontend
    url: https://contacts.contactify.biz
  - name: PROD Contactify Admin Frontend
    url: https://contacts-admin.contactify.biz
### contactify-dev
  - name: DEV Contactify Platform Frontend
    url: https://contacts-test.contactify.biz
  - name: DEV Contactify Admin Frontend
    url: https://contacts-admin-test.contactify.biz
