owner: contactify-ag
repo: upptime

status-website:
  name: Service Status
  logoUrl: https://cdn-assets-cloud.frontify.com/s3/frontify-cloud-files-us/eyJwYXRoIjoiZnJvbnRpZnlcL2ZpbGVcL3NWUktqc3lFajRhaHFYcTQ5clV4LnN2ZyJ9:frontify:fcRM4eHeqTZ9GXlCAygoHrO1nLQNTw400fP2JYBO-3Y
  cname: status.contactify.biz
  robotsText: "User-agent: * \n Disallow: /"
  metaTags:
    - name: "robots"
      content: "noindex"

sites:
# contactify
  - name: Contactify Website
    url: https://www.contactify.io

# Digital Business Card
## Frontends
### contactify-prod
  - name: PROD Contactify Platform Frontend
    url: https://contacts.contactify.biz
  - name: PROD Contactify Admin Frontend
    url: https://contacts-admin.contactify.biz

### contactify-develop
  - name: DEV Contactify Platform Frontend
    url: https://contacts.dev.contactify.biz
  - name: DEV Contactify Admin Frontend
    url: https://contacts-admin.dev.contactify.biz

### contactify-dev
  - name: STAGE Contactify Platform Frontend
    url: https://contacts-test.contactify.biz
  - name: STAGE Contactify Admin Frontend
    url: https://contacts-admin-test.contactify.biz

# V2
## Gateway
### spaices-gw-prod
  - name: PROD V2 Frontend
    url: https://health.contactify.app/health
### spaices-gw-stage
  - name: STAGE V2 Frontend
    url: https://health.stage.contactify.app/health
### spaices-gw-develop
  - name: DEV V2 Frontend
    url: https://health.dev.contactify.app/health

### contactify-login-prod
  - name: PROD Login
    url: https://login.contactify.app
### contactify-login-stage
  - name: STAGE Login
    url: https://login.stage.contactify.app
### contactify-login-develop
  - name: DEV Login
    url: https://login.dev.contactify.app

# General
## Backends
### contactify-platform-api-prod
  - name: PROD Contactify Platform API
    url: https://contacts-api.contactify.biz/api/health
    __dangerous__body_degraded: "Degraded"

### contactify-admin-api-prod
  - name: PROD Contactify Admin API
    url: https://contacts-admin-api.contactify.biz/api/health
    __dangerous__body_degraded: "Degraded"

### contactify-platform-api-develop
  - name: DEV Contactify Platform API
    url: https://contacts-api.dev.contactify.biz/api/health
    __dangerous__body_degraded: "Degraded"

### contactify-admin-api-develop
  - name: DEV Contactify Admin API
    url: https://contacts-admin-api.dev.contactify.biz/api/health
    __dangerous__body_degraded: "Degraded"

### contactify-platform-api-dev
  - name: STAGE Contactify Platform API
    url: https://contacts-api.stage.contactify.biz/api/health
    __dangerous__body_degraded: "Degraded"

### contactify-admin-api-dev
  - name: STAGE Contactify Admin API
    url: https://contacts-admin-api.stage.contactify.biz/api/health
    __dangerous__body_degraded: "Degraded"

## SCIM
## contactify-scim-api-prod
  - name: PROD Contactify SCIM API
    url: https://scim-api.contactify.biz/api/health
    __dangerous__body_degraded: "Degraded"

## contactify-scim-api-develop
  - name: DEV Contactify SCIM API
    url: https://scim-api.dev.contactify.biz/api/health
    __dangerous__body_degraded: "Degraded"

## contactify-scim-api-dev
  - name: STAGE Contactify SCIM API
    url: https://scim-api.stage.contactify.biz/api/health
    __dangerous__body_degraded: "Degraded"

## Wallet Pass
## contactify-wallet-pass-prod
  - name: PROD Contactify Wallet Pass API
    url: https://main.walletpass.api.prod.contactify.app/api/health
    __dangerous__body_degraded: "Degraded"

## contactify-wallet-pass-stage
  - name: STAGE Contactify Wallet Pass API
    url: https://main.walletpass.api.stage.contactify.app/api/health
    __dangerous__body_degraded: "Degraded"

## contactify-wallet-pass-develop
  - name: DEV Contactify Wallet Pass API
    url: https://main.walletpass.api.dev.contactify.app/api/health
    __dangerous__body_degraded: "Degraded"

## External
### Passource
  - name: Passource Wallet Pass Generator
    url: https://www.passsource.com/api/