# Change these first
owner: contactify-ag # Your GitHub organization or username, where this repository lives
repo: upptime # The name of this repository

assignees:
  - cleverer
  - jeniffer9

sites:
# Public
  - name: Contactify Website
    url: https://www.contactify.biz
# Contactify PROD
  - name: Contactify Platform API
    url: https://contacts-api.contactify.biz
  - name: Contactify Platform Frontend
    url: https://contacts.contactify.biz
  - name: Contactify Admin API
    url: https://contacts-admin-api.contactify.biz
  - name: Contactify Admin Frontend
    url: https://contacts-admin.contactify.biz
# Contactify DEV
  - name: Contactify Platform API
    url: https://contacts-api-test.contactify.biz
  - name: Contactify Platform Frontend
    url: https://contacts-test.contactify.biz
  - name: Contactify Admin API
    url: https://contacts-admin-api-test.contactify.biz
  - name: Contactify Admin Frontend
    url: https://contacts-admin-test.contactify.biz


workflowSchedule:
  uptime: "*/10 * * * *"